name: Push to GitHub Pages on push to master
on:
  schedule:
    # every day at midnight: https://crontab.guru/every-midnight
    - cron:  '0 0 * * *'

  # Trigger the workflow on push or pull request for master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
  # Manually trigger workflow
  workflow_dispatch:

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Install linux system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 libegl1-mesa libxcb-shape0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Build widget catalog
        run: |
          pip install -U setuptools pip
          pip install orange-canvas-core pyqt5==5.15
          bash scripts/build-widget-catalog.sh

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.111.3'
 
      # Deploy to local repo
      - name: Deploy
        if: github.ref == 'refs/heads/master'
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: public
          SKIP_EMPTY_COMMITS: True
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
